name: CI/CD Pipeline for Nuxt 3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt 3 project
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --prod
        env:
          YOOKASSA_KEY: ${{ secrets.YOOKASSA_KEY }}
